services:
  users-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: users-service
    ports:
      - "${SERVER_PORT:-8084}:${SERVER_PORT:-8084}"
    environment:
      - PORT=${PORT}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - portability_net
networks:
  portability_net:
    external: true
    name: portability_prod
